### ISSUE TITLE
Remove force unwraps

### ISSUE THREAD

**Issue by DragonCat4012** [AKORA-Studios/Calq#72]
Remove force unwrapping subjcets caused by previous navigation with optional values (ex. ExamView, ImpactSegment, NewGradeScreen....)

**Comment by annie-gupta** [comment]
@DragonCat4012 , Can you please explain the issue? I am willing to contribute.

**Comment by DragonCat4012** [comment]
This refers to an issue of force unwrapping subjects or Tests on multiple occasions, i don´t think in the navigation itself there are any at this moment.

Things like the optional Subject in the examView (Examscreen.swift) would be better as non-optionals since force unwrapping isnt really a good way to deal with this

**Comment by annie-gupta** [comment]
Hi @DragonCat4012 , understood the problem here. Could you please assign this to me. Thank you.

**Comment by annie-gupta** [comment]
Hi @DragonCat4012 , created a pull request for this issue https://github.com/AKORA-Studios/Calq/pull/96
Please review. Thank you.
